content/builds/condi-mechanist.md
Changed date, build still works
=> Updated for latest balance

content/builds/condi-mechanist.md
Added "raid" and "strike" tags
=> Added tags

content/builds/condi-virtuoso.md
Spotted a typo in gear,
Berserker -> Rampager
=> Updated gear

content/builds/heal-alac-willbender.md
change espec to willbender instead of dragonhunter
=> Heal alac willbender

content/builds/heal-alac-willbender.md
Updated Raid section after live testing
=> Updated Heal alac willbender

content/builds/power-harbinger.md
=> I changed it and uploaded mine

content/builds/power-harbinger.md
Forgot to change the patch to latest, updated it.
=> Changed to current patch

content/builds/condi-tempest.md
I'm getting comfy with the number of builds we have on the site, will probably start dedicating time to actually raiding with said builds and attaching those vids to the builds as proper references.
=> Added demo of build being used in a real raid

content/builds/condi-virtuoso.md
Updated all skills with the shortcodes, also testing if I can just commit it
=> Updated all skills to the cooler version

content/builds/condi-virtuoso.md
Multiple bladesong harmony detected, changed it to use ID instead
=> Fixed error on skill

content/builds/condi-mechanist.md
Updated skills with shortcodes for icons, and added a demo for Matthias
=> Updated skills and added demo

content/builds/power-soulbeast.md
=> Added skill shortcodes

.github/CODEOWNERS, content/builds/condi-soulbeast.md, content/builds/power-soulbeast.md, content/retired/condi-soulbeast.md
updated errors and new video link
=> Condi soulbeast

content/builds/power-daredevil.md
Created Power Daredevil (still need to add the build but i have no access to GW2 right now)
=> Created Power Daredevil

content/builds/power-mechanist-sword.md, content/builds/quickness-power-harbinger.md
Added build chat code, description, and tagline
=> Launch ready

content/builds/power-spellbreaker.md
=> Power spellbreaker

content/builds/power-herald.md
Shiro and Jalis chatcodes were not showing up
=> Fixed Legendary Stances

content/builds/power-scrapper.md
=> Updated spec = "scrapper"

.github/CODEOWNERS, content/builds/alac-hybrid-scourge.md, content/builds/power-herald.md
=> Hybrid scourge

content/builds/condi-willbender.md
Heaven's Palm wrong API
Missing 1 skill
=> Fixed minor errors

content/builds/condi-virtuoso.md
Simpler rotation with less buttons.
=> Updated rotation and video

content/builds/power-herald.md
=> Updated to correct build

.github/CODEOWNERS, content/builds/condi-core-elementalist, content/builds/condi-core-elementalist.md, content/builds/power-tempest.md
=> Added Condi Core Elementalist and Power Tempest

content/builds/alac-condi-mechanist.md, content/builds/condi-tempest.md, content/builds/condi-weaver.md, content/builds/condi-willbender.md, content/builds/power-catalyst.md, content/builds/power-harbinger.md, content/builds/power-herald.md, content/builds/power-scrapper.md, content/builds/power-soulbeast.md, content/builds/power-vindicator.md, content/builds/quickness-power-harbinger.md
=> Updated to latest patch

content/builds/power-tempest.md
Testing to improve build readibility and formatting
=> Improving readability and formatting

.github/CODEOWNERS, content/builds/quickness-condi-herald.md
=> Condi quick herald

content/builds/condi-tempest.md
Updated Condition Tempest to new build format
=> Updated Condition Tempest

content/builds/alac-condi-mechanist.md, content/builds/alac-condi-mirage.md, content/builds/alac-power-mechanist.md, content/builds/condi-core-elementalist.md, content/builds/condi-mechanist.md, content/builds/condi-tempest.md, content/builds/condi-weaver.md, content/builds/condi-willbender.md, content/builds/power-daredevil.md, content/builds/power-herald.md, content/builds/power-holosmith-ECSU.md, content/builds/power-holosmith-PBM.md, content/builds/power-mechanist-hammer.md, content/builds/power-mechanist-sword.md, content/builds/power-scrapper.md, content/builds/power-soulbeast.md, content/builds/power-spellbreaker-scooby.md, content/builds/power-tempest.md, content/builds/quickness-power-harbinger.md, content/builds/quickness-power-herald.md, content/builds/rifle-mech.md
Updated builds to latest patch, added video for pRifle Mech
=> Updated builds to latest patch

content/builds/rifle-mech.md
Changed Sword & Shield to Rifle
=> Fixed weapon typo

content/builds/hybrid-tempest.md
=> Fixed typos

content/builds/power-vindicator.md
by changing the updated date so i have a page i can send to masel for review
=> Push pVindi to the back

content/builds/alac-condi-mechanist.md, content/builds/alac-power-mechanist.md, content/builds/condi-mechanist.md, content/builds/condi-reaper-mm.md, content/builds/condi-tempest.md, content/builds/condi-weaver.md, content/builds/power-daredevil.md, content/builds/power-harbinger.md, content/builds/power-herald.md, content/builds/power-holosmith-ECSU.md, content/builds/power-holosmith-PBM.md, content/builds/power-mechanist-sword.md, content/builds/power-spellbreaker-scooby.md, content/builds/quickness-power-harbinger.md, content/builds/quickness-power-herald.md, content/builds/rifle-mech.md
Left out a couple of builds that I didn't like on purpose
=> Updated updated dates of builds from patch 2025-06

content/builds/hybrid-catalyst.md, content/builds/hybrid-tempest.md
also fixed some stuff with hybrid tempest
=> Created Hybrid Catalyst
